### ISSUE TITLE
Serenity 2.8.0 Upgrade Guide

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1770]
> 2.8.0 is the first version that also contains NetStandard1.6 targeted assemblies. Asp.Net Core port for Serene is currently a work in progress, but we are not there yet. So, this is just an upgrade guide for existing users with ASP.NET MVC/.NET Framework 4.5.

Personally, i'm not a fan of Node/NPM/Bower etc, but sometimes you can't resist the change. 

For client side development they became something like standard, most javascript libraries are available in NPM/Bower, and these tools are already integrated into Visual Studio. 

NPM is also the recommended way to distribute / acquire TypeScript definition files in the form of `npm install @types/jquery` etc.

> Actually Bower, which is just another NPM package for client side libraries, looks like being deprecated and replaced by NPM itself.

So we are gonna start by using NPM for TypeScript definitions, instead of xyz.TypeScript.DefinitelyTyped NuGet packages.

> Another reason i have to do this is, content files in NuGet packages are no longer supported for ASP.NET Core project.json based projects, so we can't distribute .d.ts files with them.

After updating Serenity as usual, you'll have many TypeScript errors.

* First, start by ensuring that you have a `Serenity.CoreLib.d.ts` file under `scripts\typings\serenity`. This is the new location for this file.

* Then delete the old one at `scripts\serenity\Serenity.CoreLib.d.ts` (if you have any).

Now most of errors should be gone. When you open new `Serenity.CoreLib.d.ts` file or build your project you'll have a few errors like below:

```
Cannot find type definition file for 'jquery'.
Cannot find type definition file for 'jquery.validation'.
Cannot find type definition file for 'jqueryui'.
```

To resolve these, we have to install them with NPM.

First create a `package.json` file under YourApplication.Web project (where tsconfig.json and web.config resides).

Here is a sample one:

```json
{
  "name": "serene.web",
  "version": "1.0.0",
  "description": "My Application Description",
  "main": "index.js",
  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.32"
  },
  "devDependencies": {},
  "scripts": {
  },
  "author": "",
  "license": "ISC"
}
```

Replace `serene.web` with your app name.

Open a command prompt in the folder Serene.Web.csproj (YourProject.Web.csproj) exists.

> Right click on project name, open folder in explorer, open a command prompt from explorer File menu.

Type 

```cmd
C:\..\Serene.Web> npm
```

to make sure that you have Node/NPM installed. 

If not, install it from https://nodejs.org/en/download/ (LTS is recommended)

Again make sure that you are where web.config file resides (project root), then type:

```
C:\..\Serene.Web> npm install
```

You should now have a `node_modules` folder with a `@types` folder inside, under current directory.

> If you are using git, make sure you add `node_modules/` to `.gitignore` file.

Open package manager console and uninstall following packages:

```ps
Uninstall-Package toastr.TypeScript.DefinitelyTyped
Uninstall-Package sortablejs.TypeScript.DefinitelyTyped
Uninstall-Package jspdf.TypeScript.DefinitelyTyped
Uninstall-Package jquery.blockUI.TypeScript.DefinitelyTyped
Uninstall-Package jquery.cookie.TypeScript.DefinitelyTyped
Uninstall-Package jqueryui.TypeScript.DefinitelyTyped
Uninstall-Package jquery.validation.TypeScript.DefinitelyTyped
Uninstall-Package jquery.TypeScript.DefinitelyTyped
```

Now your project should build without any errors.

> Next step will be to move jQuery, jQuery-UI etc scripts to NPM but it is for another version.

**Comment by KhatamiMasoud** [comment]
After upgrade to 2.8 from 2.6 and doing above instruction this error happened:
C:\Program Files\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "dotnet-sergen, Version=2.8.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by volkanceylan** [comment]
What are you doing with dotnet-sergen i wonder. It is .NET core, this is about .NET framework.

**Comment by KhatamiMasoud** [comment]
I Remove
    <Reference Include="dotnet-sergen, Version=2.8.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Serenity.CodeGenerator.2.8.0\lib\netcoreapp1.0\dotnet-sergen.dll</HintPath>
      <Private>True</Private>
    </Reference>
from .csproj
It's work.
thanks

**Comment by volkanceylan** [comment]
How did you install it into your project, can you explain?

**Comment by KhatamiMasoud** [comment]
I Just Upgrade with
Update-Package Serenity.Web
Update-Package Serenity.CodeGenerator
and doing npm installation.

**Comment by volkanceylan** [comment]
I did same but couldn't manage to add a reference. Probably bug with your NuGet version

**Comment by KhatamiMasoud** [comment]
Ok. Thanks for your quick answering.

**Comment by rgilsimoes** [comment]
Hi,

I'm having this issue after 2.8. upgrade:

Modules/Common/Reporting/PdfExportHelper.ts(115,35): warning TS2304: Cannot find name 'jsPDF'

Any help would be appreciated!

**Comment by volkanceylan** [comment]
Check your TypeScript version.

**Comment by volkanceylan** [comment]
And follow upgrade guide properly please.

**Comment by rgilsimoes** [comment]
Typescript version is 2.0
Node_modules dir was not included in project.
Thanks!

**Comment by volkanceylan** [comment]
node_modules shouldn't be included in project but ok if that fixed your problem.

**Comment by edson** [comment]
@rgilsimoes  

Check if you have

`declare var jsPDF;`

at the beggining of PdfExportHelper.ts... if it's missing, add it... I had an old version of that file so had to add this line.

Best Regards

**Comment by rgilsimoes** [comment]
@edson sugestion worked after excluding "node_modules" again from project.

**Comment by Xynratron** [comment]
We  had a similar issue with **dotnet-sergen** like **KhatamiMasoud**, but while creating a new project, not upgrading. 
For the .Net Framework Version of the Project Template, a reference to dotnet-sergen was added, which then caused the assembly load error. Removing the reference didn't help. 

This happens when you use Visual Studio 2015 Update 1. After upgrading to "Update 3" everything works as expected.

**Comment by xareas** [comment]
Updated, I had no problems

**Comment by sayuga** [comment]
Same here. Pretty straightforward. No issues.

**Comment by wirble** [comment]
I had to add the line: as @edson mentioned

`declare var jsPDF;`

I also had the required directive error, upgrading typescript from 1.7 to the latest 2.1 fixed it.

**Comment by lquantz** [comment]
Unfortunately I'm saw the dotnet-sergen error as well, before updating VS 2015 to update 3.

Created a new Serene solution yesterday using the online template, got an error stating "_Could not load file or assembly 'dotnet-sergen' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference_", edited the csproj as @KhatamiMasoud did and removed the dotnet-sergen setting.  Made no difference.

I then upgraded to VS 2015 update 3 and rebuilt the solution.  Still got the same error.  I then created another Serene solution, again using the template, and this time it worked.

**Comment by shailendrasingh03** [comment]
post update if i do transomarm all t4 template giving error and on website is not working  
![image]()
![image](https://cloud.githubusercontent.com/assets/13510729/23187031/be3c84ca-f8a2-11e6-9b4b-fccd4cc41bd2.png)

**Comment by JoshDiDuca** [comment]
![upgrade](https://cloud.githubusercontent.com/assets/24326522/23472399/90caa9d8-fea4-11e6-81a7-18f3a5fa9776.png)

Upgrade from 2.6-2.9, followed every step but receiving errors in files such as LanguageSelection.ts etc

**Comment by jUST220** [comment]
@JoshDiDuca have you solved this problem ?

**Comment by john20xdoe** [comment]
@JoshDiDuca your typescript version probably is still 1.*...upgrade to Typescript 2.*, since it has a new attribute for the `/// <reference>` code.

E.g. ` /// <reference types="toastr" /> ` where `types` is not recognized by 1.*.

Note also that typescript 2.* needs Visual Studio Update 3.

**Comment by john20xdoe** [comment]
This guide is also relevant as additional steps: #1342
