### ISSUE TITLE
update from 3.12 to 3.14 ,after runing tsc, Serenity.CoreLib.d.ts throw 155 error

### ISSUE THREAD

**Issue by haoas** [volkanceylan/Serenity#5149]
After update from 3.12 to 3.14,I run  sergen restore  and tsc ,Serenity.CoreLib.d.ts throw 155 error.
`typings/serenity/Serenity.CoreLib.d.ts:3509:13 - error TS1086: An accessor cannot be declared in an ambient context.

3509         get cascadeValue(): any;
                 ~~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3511:13 - error TS1086: An accessor cannot be declared in an ambient context.

3511         set cascadeValue(value: any);
                 ~~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3513:13 - error TS1086: An accessor cannot be declared in an ambient context.

3513         get filterField(): string;
                 ~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3515:13 - error TS1086: An accessor cannot be declared in an ambient context.

3515         set filterField(value: string);
                 ~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3517:13 - error TS1086: An accessor cannot be declared in an ambient context.

3517         get filterValue(): any;
                 ~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3519:13 - error TS1086: An accessor cannot be declared in an ambient context.

3519         set filterValue(value: any);
                 ~~~~~~~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3660:13 - error TS1086: An accessor cannot be declared in an ambient context.

3660         get value(): string;
                 ~~~~~

typings/serenity/Serenity.CoreLib.d.ts:3662:13 - error TS1086: An accessor cannot be declared in an ambient context.

3662         set value(v: string);`

**Comment by volkanceylan** [comment]
Update your Visual Studio and typescript
